# Generated by Django 5.1.5 on 2025-01-20 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='granted_by_admin',
        ),
    ]
