# Generated by Django 5.1.5 on 2025-01-20 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_logentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogEntry',
        ),
    ]
