# Generated by Django 5.1.5 on 2025-01-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание профессии')),
                ('image_path', models.CharField(help_text='Путь к графику, сохранённому в папке static.', max_length=255, verbose_name='Путь к изображению')),
            ],
        ),
    ]
