# Generated by Django 5.1.5 on 2025-01-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VacanciesPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancies_count', models.PositiveSmallIntegerField(help_text='Количество вакансий, которое необходимо выводить на странице (не рекомендуется ставить больше 10)', verbose_name='Количество вакансий')),
                ('page_title', models.TextField(verbose_name='Заголовок страницы')),
            ],
        ),
    ]
